server:
  port: 1818 
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update   
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher